apiVersion: v1
kind: Service
metadata:
  name: {{ include "pyhchart.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "pyhchart.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
      {{- toYaml .Values.service.annotations | nindent 6 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "pyhchart.selectorLabels" . | nindent 4 }}
